### ISSUE TITLE
[chore] 깃 스쿼시 머지 적용

### ISSUE THREAD

**Issue by jycforest29** [JMS1208/SearchPharmacy#2]
main 브랜치의 34개 커밋 중 33개가 update README.md 인데 스쿼시 머지 날려서 커밋 하나로 줄이는 게 어떨까 합니다~

**Comment by jycforest29** [comment]
추가로 메인 브랜치에 가장 최근 커밋이 존재하는 브랜치 머지 하는거 어떠신가요?

**Comment by JMS1208** [comment]
혹시 카톡주실 수 있을까여 ?

2023년 5월 18일 (목) 오후 6:38, Juyeon Choi ***@***.***>님이 작성:
